configs:
    jdbcUrl: "jdbc:clickhouse://localhost:8123/"
    username: ""
    password: ""
    tableName: "db2_database"
    schemaName: "db2"
    columnsMap:
        mon_instance: "mon_instance"
        mon_dt: "mon_dt"
        mon_delta: "mon_delta"
        member: "member"
        connections_top: "connections_top"
        agents_top: "agents_top"
        coord_agents_top: "coord_agents_top"
        appls_cur_cons: "appls_cur_cons"
        appls_in_db2: "appls_in_db2"
        num_assoc_agents: "num_assoc_agents"
        num_coord_agents: "num_coord_agents"
        num_locks_held: "num_locks_held"
        num_locks_waiting: "num_locks_waiting"
        lock_list_in_use: "lock_list_in_use"
        active_sorts: "active_sorts"
        active_hash_joins: "active_hash_joins"
        active_olap_funcs: "active_olap_funcs"
        num_pooled_agents: "num_pooled_agents"
        stats_cache_size: "stats_cache_size"
        active_hash_grpbys: "active_hash_grpbys"
        sort_heap_allocated: "sort_heap_allocated"
        sort_shrheap_allocated: "sort_shrheap_allocated"
        sort_shrheap_top: "sort_shrheap_top"
        active_hash_grpbys_top: "active_hash_grpbys_top"
        active_hash_joins_top: "active_hash_joins_top"
        active_olap_funcs_top: "active_olap_funcs_top"
        active_peas: "active_peas"
        active_peas_top: "active_peas_top"
        active_peds: "active_peds"
        active_peds_top: "active_peds_top"
        active_sort_consumers: "active_sort_consumers"
        active_sort_consumers_top: "active_sort_consumers_top"
        active_sorts_top: "active_sorts_top"
        sort_consumer_heap_top: "sort_consumer_heap_top"
        sort_consumer_shrheap_top: "sort_consumer_shrheap_top"
        sort_heap_top: "sort_heap_top"
        total_cons: "total_cons"
        total_sec_cons: "total_sec_cons"
        act_aborted_total: "act_aborted_total"
        act_completed_total: "act_completed_total"
        act_rejected_total: "act_rejected_total"
        agent_wait_time: "agent_wait_time"
        agent_waits_total: "agent_waits_total"
        pool_data_l_reads: "pool_data_l_reads"
        pool_index_l_reads: "pool_index_l_reads"
        pool_temp_data_l_reads: "pool_temp_data_l_reads"
        pool_temp_index_l_reads: "pool_temp_index_l_reads"
        pool_temp_xda_l_reads: "pool_temp_xda_l_reads"
        pool_xda_l_reads: "pool_xda_l_reads"
        pool_data_p_reads: "pool_data_p_reads"
        pool_index_p_reads: "pool_index_p_reads"
        pool_temp_data_p_reads: "pool_temp_data_p_reads"
        pool_temp_index_p_reads: "pool_temp_index_p_reads"
        pool_temp_xda_p_reads: "pool_temp_xda_p_reads"
        pool_xda_p_reads: "pool_xda_p_reads"
        pool_data_writes: "pool_data_writes"
        pool_index_writes: "pool_index_writes"
        pool_xda_writes: "pool_xda_writes"
        pool_read_time: "pool_read_time"
        pool_write_time: "pool_write_time"
        client_idle_wait_time: "client_idle_wait_time"
        deadlocks: "deadlocks"
        direct_reads: "direct_reads"
        direct_read_time: "direct_read_time"
        direct_read_reqs: "direct_read_reqs"
        direct_writes: "direct_writes"
        direct_write_time: "direct_write_time"
        direct_write_reqs: "direct_write_reqs"
        fcm_recv_volume: "fcm_recv_volume"
        fcm_recvs_total: "fcm_recvs_total"
        fcm_recv_wait_time: "fcm_recv_wait_time"
        fcm_send_volume: "fcm_send_volume"
        fcm_sends_total: "fcm_sends_total"
        fcm_send_wait_time: "fcm_send_wait_time"
        ipc_recv_volume: "ipc_recv_volume"
        ipc_recvs_total: "ipc_recvs_total"
        ipc_recv_wait_time: "ipc_recv_wait_time"
        ipc_send_volume: "ipc_send_volume"
        ipc_sends_total: "ipc_sends_total"
        ipc_send_wait_time: "ipc_send_wait_time"
        lock_escals: "lock_escals"
        lock_escals_maxlocks: "lock_escals_maxlocks"
        lock_escals_locklist: "lock_escals_locklist"
        lock_timeouts: "lock_timeouts"
        lock_wait_time: "lock_wait_time"
        lock_waits: "lock_waits"
        log_buffer_wait_time: "log_buffer_wait_time"
        num_log_buffer_full: "num_log_buffer_full"
        log_disk_wait_time: "log_disk_wait_time"
        log_disk_waits_total: "log_disk_waits_total"
        rqsts_completed_total: "rqsts_completed_total"
        rows_modified: "rows_modified"
        rows_read: "rows_read"
        rows_returned: "rows_returned"
        tcpip_recv_volume: "tcpip_recv_volume"
        tcpip_recvs_total: "tcpip_recvs_total"
        tcpip_recv_wait_time: "tcpip_recv_wait_time"
        tcpip_send_volume: "tcpip_send_volume"
        tcpip_sends_total: "tcpip_sends_total"
        tcpip_send_wait_time: "tcpip_send_wait_time"
        app_rqsts_completed_total: "app_rqsts_completed_total"
        total_app_rqst_time: "total_app_rqst_time"
        total_rqst_time: "total_rqst_time"
        wlm_queue_time_total: "wlm_queue_time_total"
        wlm_queue_assignments_total: "wlm_queue_assignments_total"
        total_rqst_mapped_in: "total_rqst_mapped_in"
        total_rqst_mapped_out: "total_rqst_mapped_out"
        total_cpu_time: "total_cpu_time"
        total_wait_time: "total_wait_time"
        total_section_sort_time: "total_section_sort_time"
        total_section_sort_proc_time: "total_section_sort_proc_time"
        total_section_sorts: "total_section_sorts"
        total_sorts: "total_sorts"
        post_threshold_sorts: "post_threshold_sorts"
        post_shrthreshold_sorts: "post_shrthreshold_sorts"
        sort_overflows: "sort_overflows"
        total_compile_time: "total_compile_time"
        total_compile_proc_time: "total_compile_proc_time"
        total_compilations: "total_compilations"
        total_implicit_compile_time: "total_implicit_compile_time"
        total_implicit_compile_proc_time: "total_implicit_compile_proc_time"
        total_implicit_compilations: "total_implicit_compilations"
        total_section_time: "total_section_time"
        total_section_proc_time: "total_section_proc_time"
        total_app_section_executions: "total_app_section_executions"
        total_act_time: "total_act_time"
        total_act_wait_time: "total_act_wait_time"
        act_rqsts_total: "act_rqsts_total"
        total_routine_time: "total_routine_time"
        total_routine_invocations: "total_routine_invocations"
        total_commit_time: "total_commit_time"
        total_commit_proc_time: "total_commit_proc_time"
        total_app_commits: "total_app_commits"
        int_commits: "int_commits"
        total_rollback_time: "total_rollback_time"
        total_rollback_proc_time: "total_rollback_proc_time"
        total_app_rollbacks: "total_app_rollbacks"
        int_rollbacks: "int_rollbacks"
        total_runstats_time: "total_runstats_time"
        total_runstats_proc_time: "total_runstats_proc_time"
        total_runstats: "total_runstats"
        total_reorg_time: "total_reorg_time"
        total_reorg_proc_time: "total_reorg_proc_time"
        total_reorgs: "total_reorgs"
        total_load_time: "total_load_time"
        total_load_proc_time: "total_load_proc_time"
        total_loads: "total_loads"
        cat_cache_inserts: "cat_cache_inserts"
        cat_cache_lookups: "cat_cache_lookups"
        pkg_cache_inserts: "pkg_cache_inserts"
        pkg_cache_lookups: "pkg_cache_lookups"
        thresh_violations: "thresh_violations"
        num_lw_thresh_exceeded: "num_lw_thresh_exceeded"
        audit_events_total: "audit_events_total"
        audit_file_writes_total: "audit_file_writes_total"
        audit_file_write_wait_time: "audit_file_write_wait_time"
        audit_subsystem_waits_total: "audit_subsystem_waits_total"
        audit_subsystem_wait_time: "audit_subsystem_wait_time"
        diaglog_writes_total: "diaglog_writes_total"
        diaglog_write_wait_time: "diaglog_write_wait_time"
        fcm_message_recvs_total: "fcm_message_recvs_total"
        fcm_message_recv_volume: "fcm_message_recv_volume"
        fcm_message_recv_wait_time: "fcm_message_recv_wait_time"
        fcm_message_sends_total: "fcm_message_sends_total"
        fcm_message_send_volume: "fcm_message_send_volume"
        fcm_message_send_wait_time: "fcm_message_send_wait_time"
        fcm_tq_recvs_total: "fcm_tq_recvs_total"
        fcm_tq_recv_volume: "fcm_tq_recv_volume"
        fcm_tq_recv_wait_time: "fcm_tq_recv_wait_time"
        fcm_tq_sends_total: "fcm_tq_sends_total"
        fcm_tq_send_volume: "fcm_tq_send_volume"
        fcm_tq_send_wait_time: "fcm_tq_send_wait_time"
        total_routine_user_code_proc_time: "total_routine_user_code_proc_time"
        total_routine_user_code_time: "total_routine_user_code_time"
        tq_tot_send_spills: "tq_tot_send_spills"
        evmon_wait_time: "evmon_wait_time"
        evmon_waits_total: "evmon_waits_total"
        total_extended_latch_wait_time: "total_extended_latch_wait_time"
        total_extended_latch_waits: "total_extended_latch_waits"
        total_stats_fabrication_time: "total_stats_fabrication_time"
        total_stats_fabrication_proc_time: "total_stats_fabrication_proc_time"
        total_stats_fabrications: "total_stats_fabrications"
        total_sync_runstats_time: "total_sync_runstats_time"
        total_sync_runstats_proc_time: "total_sync_runstats_proc_time"
        total_sync_runstats: "total_sync_runstats"
        total_disp_run_queue_time: "total_disp_run_queue_time"
        total_peds: "total_peds"
        disabled_peds: "disabled_peds"
        post_threshold_peds: "post_threshold_peds"
        total_peas: "total_peas"
        post_threshold_peas: "post_threshold_peas"
        tq_sort_heap_requests: "tq_sort_heap_requests"
        tq_sort_heap_rejections: "tq_sort_heap_rejections"
        pool_queued_async_data_reqs: "pool_queued_async_data_reqs"
        pool_queued_async_index_reqs: "pool_queued_async_index_reqs"
        pool_queued_async_xda_reqs: "pool_queued_async_xda_reqs"
        pool_queued_async_temp_data_reqs: "pool_queued_async_temp_data_reqs"
        pool_queued_async_temp_index_reqs: "pool_queued_async_temp_index_reqs"
        pool_queued_async_temp_xda_reqs: "pool_queued_async_temp_xda_reqs"
        pool_queued_async_other_reqs: "pool_queued_async_other_reqs"
        pool_queued_async_data_pages: "pool_queued_async_data_pages"
        pool_queued_async_index_pages: "pool_queued_async_index_pages"
        pool_queued_async_xda_pages: "pool_queued_async_xda_pages"
        pool_queued_async_temp_data_pages: "pool_queued_async_temp_data_pages"
        pool_queued_async_temp_index_pages: "pool_queued_async_temp_index_pages"
        pool_queued_async_temp_xda_pages: "pool_queued_async_temp_xda_pages"
        pool_failed_async_data_reqs: "pool_failed_async_data_reqs"
        pool_failed_async_index_reqs: "pool_failed_async_index_reqs"
        pool_failed_async_xda_reqs: "pool_failed_async_xda_reqs"
        pool_failed_async_temp_data_reqs: "pool_failed_async_temp_data_reqs"
        pool_failed_async_temp_index_reqs: "pool_failed_async_temp_index_reqs"
        pool_failed_async_temp_xda_reqs: "pool_failed_async_temp_xda_reqs"
        pool_failed_async_other_reqs: "pool_failed_async_other_reqs"
        prefetch_wait_time: "prefetch_wait_time"
        prefetch_waits: "prefetch_waits"
        app_act_completed_total: "app_act_completed_total"
        app_act_aborted_total: "app_act_aborted_total"
        app_act_rejected_total: "app_act_rejected_total"
        total_connect_request_time: "total_connect_request_time"
        total_connect_request_proc_time: "total_connect_request_proc_time"
        total_connect_requests: "total_connect_requests"
        total_connect_authentication_time: "total_connect_authentication_time"
        total_connect_authentication_proc_time: "total_connect_authentication_proc_time"
        total_connect_authentications: "total_connect_authentications"
        comm_exit_wait_time: "comm_exit_wait_time"
        comm_exit_waits: "comm_exit_waits"
        pool_async_data_reads: "pool_async_data_reads"
        pool_async_data_read_reqs: "pool_async_data_read_reqs"
        pool_async_data_writes: "pool_async_data_writes"
        pool_async_index_reads: "pool_async_index_reads"
        pool_async_index_read_reqs: "pool_async_index_read_reqs"
        pool_async_index_writes: "pool_async_index_writes"
        pool_async_xda_reads: "pool_async_xda_reads"
        pool_async_xda_read_reqs: "pool_async_xda_read_reqs"
        pool_async_xda_writes: "pool_async_xda_writes"
        pool_no_victim_buffer: "pool_no_victim_buffer"
        pool_lsn_gap_clns: "pool_lsn_gap_clns"
        pool_drty_pg_steal_clns: "pool_drty_pg_steal_clns"
        pool_drty_pg_thrsh_clns: "pool_drty_pg_thrsh_clns"
        vectored_ios: "vectored_ios"
        pages_from_vectored_ios: "pages_from_vectored_ios"
        block_ios: "block_ios"
        pages_from_block_ios: "pages_from_block_ios"
        unread_prefetch_pages: "unread_prefetch_pages"
        files_closed: "files_closed"
        pool_async_read_time: "pool_async_read_time"
        pool_async_write_time: "pool_async_write_time"
        skipped_prefetch_data_p_reads: "skipped_prefetch_data_p_reads"
        skipped_prefetch_index_p_reads: "skipped_prefetch_index_p_reads"
        skipped_prefetch_xda_p_reads: "skipped_prefetch_xda_p_reads"
        skipped_prefetch_temp_data_p_reads: "skipped_prefetch_temp_data_p_reads"
        skipped_prefetch_temp_index_p_reads: "skipped_prefetch_temp_index_p_reads"
        skipped_prefetch_temp_xda_p_reads: "skipped_prefetch_temp_xda_p_reads"
        skipped_prefetch_uow_data_p_reads: "skipped_prefetch_uow_data_p_reads"
        skipped_prefetch_uow_index_p_reads: "skipped_prefetch_uow_index_p_reads"
        skipped_prefetch_uow_xda_p_reads: "skipped_prefetch_uow_xda_p_reads"
        skipped_prefetch_uow_temp_data_p_reads: "skipped_prefetch_uow_temp_data_p_reads"
        skipped_prefetch_uow_temp_index_p_reads: "skipped_prefetch_uow_temp_index_p_reads"
        skipped_prefetch_uow_temp_xda_p_reads: "skipped_prefetch_uow_temp_xda_p_reads"
        rows_deleted: "rows_deleted"
        rows_inserted: "rows_inserted"
        rows_updated: "rows_updated"
        total_hash_joins: "total_hash_joins"
        total_hash_loops: "total_hash_loops"
        hash_join_overflows: "hash_join_overflows"
        hash_join_small_overflows: "hash_join_small_overflows"
        post_shrthreshold_hash_joins: "post_shrthreshold_hash_joins"
        total_olap_funcs: "total_olap_funcs"
        olap_func_overflows: "olap_func_overflows"
        dynamic_sql_stmts: "dynamic_sql_stmts"
        static_sql_stmts: "static_sql_stmts"
        failed_sql_stmts: "failed_sql_stmts"
        select_sql_stmts: "select_sql_stmts"
        uid_sql_stmts: "uid_sql_stmts"
        ddl_sql_stmts: "ddl_sql_stmts"
        merge_sql_stmts: "merge_sql_stmts"
        xquery_stmts: "xquery_stmts"
        call_sql_stmts: "call_sql_stmts"
        implicit_rebinds: "implicit_rebinds"
        binds_precompiles: "binds_precompiles"
        int_rows_deleted: "int_rows_deleted"
        int_rows_inserted: "int_rows_inserted"
        int_rows_updated: "int_rows_updated"
        post_threshold_hash_joins: "post_threshold_hash_joins"
        pkg_cache_num_overflows: "pkg_cache_num_overflows"
        cat_cache_overflows: "cat_cache_overflows"
        total_async_runstats: "total_async_runstats"
        total_hash_grpbys: "total_hash_grpbys"
        hash_grpby_overflows: "hash_grpby_overflows"
        post_threshold_hash_grpbys: "post_threshold_hash_grpbys"
        post_threshold_olap_funcs: "post_threshold_olap_funcs"
        total_backup_time: "total_backup_time"
        total_backup_proc_time: "total_backup_proc_time"
        total_backups: "total_backups"
        total_index_build_time: "total_index_build_time"
        total_index_build_proc_time: "total_index_build_proc_time"
        total_indexes_built: "total_indexes_built"
        ida_send_wait_time: "ida_send_wait_time"
        ida_sends_total: "ida_sends_total"
        ida_send_volume: "ida_send_volume"
        ida_recv_wait_time: "ida_recv_wait_time"
        ida_recvs_total: "ida_recvs_total"
        ida_recv_volume: "ida_recv_volume"
        fcm_tq_recv_waits_total: "fcm_tq_recv_waits_total"
        fcm_message_recv_waits_total: "fcm_message_recv_waits_total"
        fcm_tq_send_waits_total: "fcm_tq_send_waits_total"
        fcm_message_send_waits_total: "fcm_message_send_waits_total"
        fcm_send_waits_total: "fcm_send_waits_total"
        fcm_recv_waits_total: "fcm_recv_waits_total"
    batchSize: 1
