configs:
    jdbcUrl: "jdbc:clickhouse://localhost:8123/"
    username: ""
    password: ""
    tableName: "db2_pkgcache"
    schemaName: "db2"
    columnsMap:
        mon_instance: "mon_instance"
        mon_dt: "mon_dt"
        mon_delta: "mon_delta"
        package_schema: "package_schema"
        package_name: "package_name"
        package_version_id: "package_version_id"
        section_number: "section_number"
        section_type: "section_type"
        stmt_type_id: "stmt_type_id"
        effective_isolation: "effective_isolation"
        stmt_text: "stmt_text"
        semantic_env_id: "semantic_env_id"
        stmtid: "stmtid"
        planid: "planid"
        executable_id: "executable_id"
        stmt_pkg_cache_id: "stmt_pkg_cache_id"
        insert_timestamp: "insert_timestamp"
        prep_time: "prep_time"
        query_cost_estimate: "query_cost_estimate"
        max_coord_stmt_exec_time: "max_coord_stmt_exec_time"
        num_working_copies: "num_working_copies"
        prep_warning: "prep_warning"
        prep_warning_reason: "prep_warning_reason"
        active_hash_grpbys_top: "active_hash_grpbys_top"
        active_hash_joins_top: "active_hash_joins_top"
        active_olap_funcs_top: "active_olap_funcs_top"
        active_peas_top: "active_peas_top"
        active_peds_top: "active_peds_top"
        active_sort_consumers_top: "active_sort_consumers_top"
        active_sorts_top: "active_sorts_top"
        sort_consumer_heap_top: "sort_consumer_heap_top"
        sort_consumer_shrheap_top: "sort_consumer_shrheap_top"
        sort_heap_top: "sort_heap_top"
        sort_shrheap_top: "sort_shrheap_top"
        num_routines: "num_routines"
        num_executions: "num_executions"
        num_exec_with_metrics: "num_exec_with_metrics"
        total_act_time: "total_act_time"
        total_act_wait_time: "total_act_wait_time"
        total_cpu_time: "total_cpu_time"
        pool_read_time: "pool_read_time"
        pool_write_time: "pool_write_time"
        direct_read_time: "direct_read_time"
        direct_write_time: "direct_write_time"
        lock_wait_time: "lock_wait_time"
        total_section_sort_time: "total_section_sort_time"
        total_section_sort_proc_time: "total_section_sort_proc_time"
        total_section_sorts: "total_section_sorts"
        lock_escals: "lock_escals"
        lock_waits: "lock_waits"
        rows_modified: "rows_modified"
        rows_read: "rows_read"
        rows_returned: "rows_returned"
        direct_reads: "direct_reads"
        direct_read_reqs: "direct_read_reqs"
        direct_writes: "direct_writes"
        direct_write_reqs: "direct_write_reqs"
        pool_data_l_reads: "pool_data_l_reads"
        pool_temp_data_l_reads: "pool_temp_data_l_reads"
        pool_xda_l_reads: "pool_xda_l_reads"
        pool_temp_xda_l_reads: "pool_temp_xda_l_reads"
        pool_index_l_reads: "pool_index_l_reads"
        pool_temp_index_l_reads: "pool_temp_index_l_reads"
        pool_data_p_reads: "pool_data_p_reads"
        pool_temp_data_p_reads: "pool_temp_data_p_reads"
        pool_xda_p_reads: "pool_xda_p_reads"
        pool_temp_xda_p_reads: "pool_temp_xda_p_reads"
        pool_index_p_reads: "pool_index_p_reads"
        pool_temp_index_p_reads: "pool_temp_index_p_reads"
        pool_data_writes: "pool_data_writes"
        pool_xda_writes: "pool_xda_writes"
        pool_index_writes: "pool_index_writes"
        total_sorts: "total_sorts"
        post_threshold_sorts: "post_threshold_sorts"
        post_shrthreshold_sorts: "post_shrthreshold_sorts"
        sort_overflows: "sort_overflows"
        wlm_queue_time_total: "wlm_queue_time_total"
        wlm_queue_assignments_total: "wlm_queue_assignments_total"
        deadlocks: "deadlocks"
        fcm_recv_volume: "fcm_recv_volume"
        fcm_recvs_total: "fcm_recvs_total"
        fcm_send_volume: "fcm_send_volume"
        fcm_sends_total: "fcm_sends_total"
        fcm_recv_wait_time: "fcm_recv_wait_time"
        fcm_send_wait_time: "fcm_send_wait_time"
        lock_timeouts: "lock_timeouts"
        log_buffer_wait_time: "log_buffer_wait_time"
        num_log_buffer_full: "num_log_buffer_full"
        log_disk_wait_time: "log_disk_wait_time"
        log_disk_waits_total: "log_disk_waits_total"
        num_coord_exec: "num_coord_exec"
        num_coord_exec_with_metrics: "num_coord_exec_with_metrics"
        total_routine_time: "total_routine_time"
        total_routine_invocations: "total_routine_invocations"
        coord_stmt_exec_time: "coord_stmt_exec_time"
        stmt_exec_time: "stmt_exec_time"
        total_section_time: "total_section_time"
        total_section_proc_time: "total_section_proc_time"
        total_routine_non_sect_time: "total_routine_non_sect_time"
        total_routine_non_sect_proc_time: "total_routine_non_sect_proc_time"
        lock_waits_global: "lock_waits_global"
        lock_wait_time_global: "lock_wait_time_global"
        lock_timeouts_global: "lock_timeouts_global"
        lock_escals_maxlocks: "lock_escals_maxlocks"
        lock_escals_locklist: "lock_escals_locklist"
        reclaim_wait_time: "reclaim_wait_time"
        spacemappage_reclaim_wait_time: "spacemappage_reclaim_wait_time"
        audit_events_total: "audit_events_total"
        audit_file_writes_total: "audit_file_writes_total"
        audit_file_write_wait_time: "audit_file_write_wait_time"
        audit_subsystem_waits_total: "audit_subsystem_waits_total"
        audit_subsystem_wait_time: "audit_subsystem_wait_time"
        diaglog_writes_total: "diaglog_writes_total"
        diaglog_write_wait_time: "diaglog_write_wait_time"
        fcm_message_recvs_total: "fcm_message_recvs_total"
        fcm_message_recv_volume: "fcm_message_recv_volume"
        fcm_message_recv_wait_time: "fcm_message_recv_wait_time"
        fcm_message_sends_total: "fcm_message_sends_total"
        fcm_message_send_volume: "fcm_message_send_volume"
        fcm_message_send_wait_time: "fcm_message_send_wait_time"
        fcm_tq_recvs_total: "fcm_tq_recvs_total"
        fcm_tq_recv_volume: "fcm_tq_recv_volume"
        fcm_tq_recv_wait_time: "fcm_tq_recv_wait_time"
        fcm_tq_sends_total: "fcm_tq_sends_total"
        fcm_tq_send_volume: "fcm_tq_send_volume"
        fcm_tq_send_wait_time: "fcm_tq_send_wait_time"
        num_lw_thresh_exceeded: "num_lw_thresh_exceeded"
        thresh_violations: "thresh_violations"
        total_app_section_executions: "total_app_section_executions"
        total_routine_user_code_proc_time: "total_routine_user_code_proc_time"
        total_routine_user_code_time: "total_routine_user_code_time"
        tq_tot_send_spills: "tq_tot_send_spills"
        evmon_wait_time: "evmon_wait_time"
        evmon_waits_total: "evmon_waits_total"
        total_extended_latch_wait_time: "total_extended_latch_wait_time"
        total_extended_latch_waits: "total_extended_latch_waits"
        total_disp_run_queue_time: "total_disp_run_queue_time"
        total_stats_fabrication_time: "total_stats_fabrication_time"
        total_stats_fabrications: "total_stats_fabrications"
        total_sync_runstats_time: "total_sync_runstats_time"
        total_sync_runstats: "total_sync_runstats"
        total_peds: "total_peds"
        disabled_peds: "disabled_peds"
        post_threshold_peds: "post_threshold_peds"
        total_peas: "total_peas"
        post_threshold_peas: "post_threshold_peas"
        tq_sort_heap_requests: "tq_sort_heap_requests"
        tq_sort_heap_rejections: "tq_sort_heap_rejections"
        pool_queued_async_data_reqs: "pool_queued_async_data_reqs"
        pool_queued_async_index_reqs: "pool_queued_async_index_reqs"
        pool_queued_async_xda_reqs: "pool_queued_async_xda_reqs"
        pool_queued_async_temp_data_reqs: "pool_queued_async_temp_data_reqs"
        pool_queued_async_temp_index_reqs: "pool_queued_async_temp_index_reqs"
        pool_queued_async_temp_xda_reqs: "pool_queued_async_temp_xda_reqs"
        pool_queued_async_other_reqs: "pool_queued_async_other_reqs"
        pool_queued_async_data_pages: "pool_queued_async_data_pages"
        pool_queued_async_index_pages: "pool_queued_async_index_pages"
        pool_queued_async_xda_pages: "pool_queued_async_xda_pages"
        pool_queued_async_temp_data_pages: "pool_queued_async_temp_data_pages"
        pool_queued_async_temp_index_pages: "pool_queued_async_temp_index_pages"
        pool_queued_async_temp_xda_pages: "pool_queued_async_temp_xda_pages"
        pool_failed_async_data_reqs: "pool_failed_async_data_reqs"
        pool_failed_async_index_reqs: "pool_failed_async_index_reqs"
        pool_failed_async_xda_reqs: "pool_failed_async_xda_reqs"
        pool_failed_async_temp_data_reqs: "pool_failed_async_temp_data_reqs"
        pool_failed_async_temp_index_reqs: "pool_failed_async_temp_index_reqs"
        pool_failed_async_temp_xda_reqs: "pool_failed_async_temp_xda_reqs"
        pool_failed_async_other_reqs: "pool_failed_async_other_reqs"
        prefetch_wait_time: "prefetch_wait_time"
        prefetch_waits: "prefetch_waits"
        ida_send_wait_time: "ida_send_wait_time"
        ida_sends_total: "ida_sends_total"
        ida_send_volume: "ida_send_volume"
        ida_recv_wait_time: "ida_recv_wait_time"
        ida_recvs_total: "ida_recvs_total"
        ida_recv_volume: "ida_recv_volume"
        rows_deleted: "rows_deleted"
        rows_inserted: "rows_inserted"
        rows_updated: "rows_updated"
        total_hash_joins: "total_hash_joins"
        total_hash_loops: "total_hash_loops"
        hash_join_overflows: "hash_join_overflows"
        hash_join_small_overflows: "hash_join_small_overflows"
        post_shrthreshold_hash_joins: "post_shrthreshold_hash_joins"
        total_olap_funcs: "total_olap_funcs"
        olap_func_overflows: "olap_func_overflows"
        int_rows_deleted: "int_rows_deleted"
        int_rows_inserted: "int_rows_inserted"
        int_rows_updated: "int_rows_updated"
        comm_exit_wait_time: "comm_exit_wait_time"
        comm_exit_waits: "comm_exit_waits"
        post_threshold_hash_joins: "post_threshold_hash_joins"
        total_hash_grpbys: "total_hash_grpbys"
        hash_grpby_overflows: "hash_grpby_overflows"
        post_threshold_hash_grpbys: "post_threshold_hash_grpbys"
        post_threshold_olap_funcs: "post_threshold_olap_funcs"
        total_index_build_time: "total_index_build_time"
        total_index_build_proc_time: "total_index_build_proc_time"
        total_indexes_built: "total_indexes_built"
        fcm_tq_recv_waits_total: "fcm_tq_recv_waits_total"
        fcm_message_recv_waits_total: "fcm_message_recv_waits_total"
        fcm_tq_send_waits_total: "fcm_tq_send_waits_total"
        fcm_message_send_waits_total: "fcm_message_send_waits_total"
        fcm_send_waits_total: "fcm_send_waits_total"
        fcm_recv_waits_total: "fcm_recv_waits_total"
    batchSize: 10
